/*
Module: IAuthenticationPlugin.kt
Author: Gabriel Cantergiani
 */
package br.pucrio.inf.lac.edgesecinterfaces

import java.security.Key

/*
Interface: IAuthenticationPlugin
Description: Interface for plugin that provides an authentication implementation, compatible with EdgeSec framework
 */
interface IAuthenticationPlugin {

    /*
        Returns ID of protocol implemented by plugin

        Returns:
            - String representing protocol
     */
    fun getProtocolID(): String;

    /*
        Sign data using provided key with the protocol implemented by plugin

        Parameters:
            - data: ByteArray representing data to be signed
            - key: Key object used for signature

        Returns:
            - ByteArray representing generated signature
     */
    fun sign(data: ByteArray, key: Key): ByteArray;

    /*
        Verify a signature

        Parameters:
            - data: ByteArray representing data of the signature to be verified
            - key: Key object used for signature
            - signature: ByteArray representing signature to be verified

        Returns:
            - True if signature is valid and false otherwise
     */
    fun verifySignature(data: ByteArray, key: Key, signature: ByteArray): Boolean;

    /*
        Generate a hash value using hashing function implemented by plugin

        Parameters:
            - payload: ByteArray representing payload to be hashed

        Returns:
            - ByteArray representing hash generated
     */
    fun generateHash(payload: ByteArray): ByteArray;

    /*
        Return size in bytes of the hash generated by hashing function of protocol implemented by plugin

        Returns:
            - Integer representing size of hashes generated by plugin
     */
    fun getHashSize(): Int;
}